name: valorant_randomizer
description: Projeto para randomizar personagens e armas do jogo Valorant (Riot games)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/character_icons/
    - assets/class_type/
    - assets/background/
    - assets/images/
